name: android_build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleRelease --stacktrace
      - run: mv app/build/outputs/apk/release/*.apk .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag_name }}
          name: "Android APK Release"
          body: |
            This release includes:
            - The latest APK build.
            - Built using Gradle on GitHub Actions.
