name: android_build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/gradle-build-action@v1
        with:
          gradle-version: current
          arguments: assembleRelease --stacktrace
      - run: mv app/build/outputs/apk/release/*.apk .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag_name }}
          name: "Android APK Release"
          body: |
            This release includes:
            - The latest APK build.
            - Built using Gradle on GitHub Actions.
